# -*- coding: utf-8 -*-
"""Practica_PLN_ElMo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MP5CvLkMtL_fciS2xBEf2hbuBahLszkb
"""

import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
from tqdm import tqdm

import pandas as pd
df = pd.read_csv('tcga_simple_train.csv')

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['t'], test_size=0.2, random_state=42)

# Cargamos ELMo
with tf.device('/GPU:0'):
    elmo = hub.KerasLayer(
        "https://tfhub.dev/google/elmo/3",
        signature="default",
        output_key="elmo",
        trainable=False,
        dtype=tf.string
    )

def elmo_embedding(texts, pooling="mean", batch_size=4):
    texts = texts.astype(str).tolist() if hasattr(texts, "astype") else list(texts)
    all_embeddings = []

    for i in tqdm(range(0, len(texts), batch_size)):
        batch_texts = texts[i:i + batch_size]

        # shape: (batch_size, seq_len, 1024)
        batch_embeddings = elmo(tf.constant(batch_texts)).numpy()

        if pooling == "mean":
            batch_vectors = np.mean(batch_embeddings, axis=1)
        elif pooling == "max":
            batch_vectors = np.max(batch_embeddings, axis=1)
        else:
            raise ValueError("Pooling debe ser 'mean' o 'max'")

        all_embeddings.append(batch_vectors)

    return np.vstack(all_embeddings)

X_train_elmo_mean = elmo_embedding(X_train, "mean")
X_test_elmo_mean = elmo_embedding(X_test, "mean")

X_train_elmo_max = elmo_embedding(X_train, "max")
X_test_elmo_max = elmo_embedding(X_test, "max")

from google.colab import drive
drive.mount('/content/drive')

import os

ruta = "/content/drive/MyDrive/PLN_data"
os.makedirs(ruta, exist_ok=True)

np.save("/content/drive/MyDrive/PLN_data/X_train_elmo_mean.npy", X_train_elmo_mean)
np.save("/content/drive/MyDrive/PLN_data/X_test_elmo_mean.npy", X_test_elmo_mean)

np.save("/content/drive/MyDrive/PLN_data/X_train_elmo_max.npy", X_train_elmo_max)
np.save("/content/drive/MyDrive/PLN_data/X_test_elmo_max.npy", X_test_elmo_max)